#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

if [[ "$OSTYPE" == darwin* ]]; then
    # On Mac, I use MacVim's non-GUI version
    alias g="open"
    alias pylab="ipython --pylab=tk"
fi
# Tmux stuff
alias ta="tmux a -t"
alias tn="tmux new -s"
### Aliases

# Platform-specific stuff
platform=$(uname)

alias ipynb="ipython notebook --profile=nbserver"
alias tl="tmux list-sessions"
if [[ $platform == 'Linux' ]]; then
    alias open=xdg-open
    alias g=xdg-open
    # ipython stuff
    alias pylab="ipython --pylab=tk"
    # Tmux stuff
    alias tmux="TERM=xterm-256color /usr/bin/tmux"
    alias ta="TERM=xterm-256color tmux a -t"
    alias tn="TERM=xterm-256color tmux new -s"
else
    alias ta="tmux a -t"
    alias tn="tmux new -s"
fi
#
# added by Anaconda3 2018.12 installer
# >>> conda init >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$(CONDA_REPORT_ERRORS=false '/Users/rameshvs/anaconda3/bin/conda' shell.zsh hook 2> /dev/null)"
if [ $? -eq 0 ]; then
    \eval "$__conda_setup"
else
    if [ -f "/Users/rameshvs/anaconda3/etc/profile.d/conda.sh" ]; then
        . "/Users/rameshvs/anaconda3/etc/profile.d/conda.sh"
    else
        \export PATH="/Users/rameshvs/anaconda3/bin:$PATH"
    fi
fi
CONDA_CHANGEPS1=false # conda activate base
unset __conda_setup
# <<< conda init <<<
export PATH=/Users/rameshvs/.local/openjdk/jdk-11.0.2+9/Contents/Home/bin:$PATH
export PATH=/Library/TeX/texbin:$PATH
export JAVA_HOME=/Users/rameshvs/.local/openjdk/jdk-11.0.2+9/Contents/Home:$JAVA_HOME
export PATH="/Users/rameshvs/anaconda3/bin:$PATH"
